apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ud6wpp0t8-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ud6wpp0t8-nodejs 
  name: ud6wpp0t8-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ud6wpp0t8-nodejs 
